services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${DATABASE_NAME}'
      - 'MYSQL_PASSWORD=${DATABASE_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}'
      - 'MYSQL_USER=${DATABASE_USERNAME}'
    ports:
      - '3306'
